export default {
  SET_LOCATIONS: 'SET_LOCATIONS',
  DELETE_LOCATIONS: 'DELETE_LOCATIONS',
  SET_LOCATIONS_IS_LOADED: 'SET_LOCATIONS_IS_LOADED',
  SET_VLAN: 'SET_VLAN',
  SET_VLAN_LOADED: 'SET_VLAN_LOADED',
  SET_FILTERS: 'SET_FILTERS',
  SET_AVAILABLE_FILTERS: 'SET_AVAILABLE_FILTERS',
  SET_ADD_FILTERS: 'SET_ADD_FILTERS',
  SET_SUBSCRIPTION: 'SET_SUBSCRIPTION',
  SET_SUBSCRIPTION_INFO: 'SET_SUBSCRIPTION_INFO',
  SET_SUBSCRIPTION_INFO_LOADED: 'SET_SUBSCRIPTION_INFO_LOADED',
  UNSET_SUBSCRIPTION_INFO_LOADED: 'UNSET_SUBSCRIPTION_INFO_LOADED',
  SET_CONTENT_FILTER: 'SET_CONTENT_FILTER'
}
