export const DOWNLOAD_FILE = 'DOWNLOAD_FILE'
export const UPLOAD_FILE = 'UPLOAD_FILE'
export const ATTACH_SIGNED_DOCUMENT = 'ATTACH_SIGNED_DOCUMENT'
export const CHANGE_CONTRACT_STATUS = 'CHANGE_CONTRACT_STATUS'
