export const GET_INFOLIST = 'GET_INFOLIST'

export const GET_DATA_FOR_INTERNET = 'GET_DATA_FOR_INTERNET'
export const GET_DATA_FOR_INTERNET_SUCCESS = 'GET_DATA_FOR_INTERNET_SUCCESS'
export const GET_DATA_FOR_INTERNET_ERROR = 'GET_DATA_FOR_INTERNET_ERROR'
