export const GET_REQUEST = 'GET_REQUEST'
export const GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS'
export const GET_REQUEST_ERROR = 'GET_REQUEST_ERROR'

export const FETCH_REQUEST_LIST = 'FETCH_REQUEST_LIST'
export const FETCH_ACTIVE_REQUEST_LIST = 'FETCH_ACTIVE_REQUEST_LIST'
export const CANCEL_REQUEST = 'CANCEL_REQUEST'

export const CREATE_REQUEST = 'CREATE_REQUEST'
export const CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS'
export const CREATE_REQUEST_ERROR = 'CREATE_REQUEST_ERROR'

export const GET_REQUEST_BY_ID = 'GET_REQUEST_BY_ID'

export const GET_SERVICES_BY_LOCATION = 'GET_SERVICES_BY_LOCATION'

export const ATTACH_FILE = 'ATTACH_FILE'
