export const GET_CLIENT_INFO = 'GET_CLIENT_INFO'
export const GET_CLIENT_INFO_SUCCESS = 'GET_CLIENT_INFO_SUCCESS'
export const GET_CLIENT_INFO_ERROR = 'GET_CLIENT_INFO_ERROR'
export const GET_CLIENT_INFO_REQUEST = 'GET_CLIENT_INFO_REQUEST'

export const GET_MANAGER_INFO = 'GET_MANAGER_INFO'
export const GET_MANAGER_INFO_SUCCESS = 'GET_MANAGER_INFO_SUCCESS'
export const GET_MANAGER_INFO_ERROR = 'GET_MANAGER_INFO_ERROR'

export const GET_UNSIGNED_DOCUMENTS = 'GET_UNSIGNED_DOCUMENTS'
export const GET_UNSIGNED_DOCUMENTS_SUCCESS = 'GET_UNSIGNED_DOCUMENTS_SUCCESS'
export const GET_UNSIGNED_DOCUMENTS_ERROR = 'GET_UNSIGNED_DOCUMENTS_ERROR'

export const GET_LIST_BILLING_ACCOUNT = 'GET_LIST_BILLING_ACCOUNT'
export const GET_LIST_BILLING_ACCOUNT_SUCCESS = 'GET_LIST_BILLING_ACCOUNT_SUCCESS'
export const GET_LIST_BILLING_ACCOUNT_ERROR = 'GET_LIST_BILLING_ACCOUNT_ERROR'
export const SET_ACTIVE_BILLING_ACCOUNT = 'SET_ACTIVE_BILLING_ACCOUNT'
export const SET_ACTIVE_BILLING_ACCOUNT_NUMBER = 'SET_ACTIVE_BILLING_ACCOUNT_NUMBER'

export const GET_LIST_PRODUCT_BY_ADDRESS = 'GET_LIST_PRODUCT_BY_ADDRESS'
export const GET_LIST_PRODUCT_BY_ADDRESS_SUCCESS = 'GET_LIST_PRODUCT_BY_ADDRESS_SUCCESS'
export const GET_LIST_PRODUCT_BY_ADDRESS_ERROR = 'GET_LIST_PRODUCT_BY_ADDRESS_ERROR'

export const GET_LIST_PRODUCT_BY_SERVICE = 'GET_LIST_PRODUCT_BY_SERVICE'
export const GET_LIST_PRODUCT_BY_SERVICE_SUCCESS = 'GET_LIST_PRODUCT_BY_SERVICE_SUCCESS'
export const GET_LIST_PRODUCT_BY_SERVICE_ERROR = 'GET_LIST_PRODUCT_BY_SERVICE_ERROR'

export const GET_LIST_SERVICE_BY_ADDRESS = 'GET_LIST_SERVICE_BY_ADDRESS'
export const GET_LIST_SERVICE_BY_ADDRESS_SUCCESS = 'GET_LIST_SERVICE_BY_ADDRESS_SUCCESS'
export const GET_LIST_SERVICE_BY_ADDRESS_ERROR = 'GET_LIST_SERVICE_BY_ADDRESS_ERROR'

export const GET_LIST_ADDRESS_BY_SERVICES = 'GET_LIST_ADDRESS_BY_SERVICES'
export const GET_LIST_ADDRESS_BY_SERVICES_SUCCESS = 'GET_LIST_ADDRESS_BY_SERVICES_SUCCESS'
export const GET_LIST_ADDRESS_BY_SERVICES_ERROR = 'GET_LIST_ADDRESS_BY_SERVICES_ERROR'

export const GET_PAYMENT_INFO = 'GET_PAYMENT_INFO'
export const GET_PAYMENT_INFO_SUCCESS = 'GET_PAYMENT_INFO_SUCCESS'
export const GET_PAYMENT_INFO_ERROR = 'GET_PAYMENT_INFO_ERROR'

export const GET_PROMISED_PAYMENT_INFO = 'GET_PROMISED_PAYMENT_INFO'
export const GET_PROMISED_PAYMENT_INFO_SUCCESS = 'GET_PROMISED_PAYMENT_INFO_SUCCESS'
export const GET_PROMISED_PAYMENT_INFO_ERROR = 'GET_PROMISED_PAYMENT_INFO_ERROR'
