export const GET_CLIENT_INFO = 'GET_CLIENT_INFO'
export const GET_CLIENT_INFO_SUCCESS = 'GET_CLIENT_INFO_SUCCESS'
export const GET_CLIENT_INFO_ERROR = 'GET_CLIENT_INFO_ERROR'
export const GET_CLIENT_INFO_REQUEST = 'GET_CLIENT_INFO_REQUEST'

export const GET_MANAGER_INFO = 'GET_MANAGER_INFO'
export const GET_MANAGER_INFO_SUCCESS = 'GET_MANAGER_INFO_SUCCESS'
export const GET_MANAGER_INFO_ERROR = 'GET_MANAGER_INFO_ERROR'

export const GET_UNSIGNED_DOCUMENTS = 'GET_UNSIGNED_DOCUMENTS'
export const GET_UNSIGNED_DOCUMENTS_SUCCESS = 'GET_UNSIGNED_DOCUMENTS_SUCCESS'
export const GET_UNSIGNED_DOCUMENTS_ERROR = 'GET_UNSIGNED_DOCUMENTS_ERROR'
