export const USER_EXISTS_WITH_SAME = 'User exists with same'
export const USER_FOUND_BY_PHONE = 'Уже существует УЗ с таким phone'
export const USER_EXISTS_WITH_EMAIL = 'Уже существует УЗ с таким email'
export const USER_EXISTS_WITH_PHONE_UPDATE = 'Another user found by phone'
export const USER_EXISTS_WITH_EMAIL_UPDATE = 'User exists with same username or email'
