const SHOW_IN_SSP_RU = 'Нет';
const SHOW_IN_SSP_EN = 'No';
const MANDATORY_01 = '7777001';
const MANDATORY_02 = '7777002';
const QUESTION_IS_REQUIRED = MANDATORY_01;
const QUESTION_NOT_REQUIRED = MANDATORY_02;
const QUESTION_SENDED = 'Отправлен';
const QUESTION_CANCELED = 'Отменен';
// анкета пройдена
const SURVEY_STATUS_DONE = 'Отвечен';
const SURVEY_STATUS_OPENED = 'Открыт';
// пользователь отменил за
const SURVEY_STATUS_CANCELED = 'Отменен';
const SURVEY_STATUS_SENDED = 'Отправлен';
const SURVEY_PUTOFF_DAYS = 10;
const SURVEY_MAX_POSTPONED_TIMES = 3;
const QUESTION_TYPE_TEXT = 'Произвольный Ответ';
export { SHOW_IN_SSP_EN, SHOW_IN_SSP_RU, MANDATORY_02, QUESTION_CANCELED, QUESTION_SENDED, QUESTION_TYPE_TEXT, QUESTION_NOT_REQUIRED, QUESTION_IS_REQUIRED, SURVEY_STATUS_CANCELED, SURVEY_STATUS_DONE, SURVEY_STATUS_OPENED, SURVEY_STATUS_SENDED, SURVEY_PUTOFF_DAYS, SURVEY_MAX_POSTPONED_TIMES };
//# sourceMappingURL=survey.js.map