export const BACKEND_TESTING = '.lk-backend.b2bweb.t2.ertelecom.ru'
export const BACKEND_COMBAT = 'api-lkb2b.domru.ru'
export const FRONTEND_LOCALHOST = 'localhost:8080'
export const FRONTEND_TESTING = 'frontend2.b2bweb.t2.ertelecom.ru'
export const FRONTEND_COMBAT = 'beta-lkb2b.domru.ru'
export const FRONTEND_STAGING = 'lkb2bnew.staging.ertelecom.ru'
export const BACKEND_STAGING = 'api-lkb2b.staging.ertelecom.ru'
