export const BACKEND_TESTING = '.lk-backend.b2bweb.t2.ertelecom.ru'
export const BACKEND_COMBAT = 'api-lkb2b.domru.ru'
export const FRONTEND_LOCALHOST = 'localhost:8080'
export const FRONTEND_TESTING = 'frontend2.b2bweb.t2.ertelecom.ru'
export const FRONTEND_COMBAT = 'newlkb2b.domru.ru'
export const FRONTEND_STAGING = 'lkb2bnew.domru.staging.ertelecom.ru'
export const BACKEND_STAGING = 'api-lkb2b.domru.staging.ertelecom.ru'
export const SSO_CHANGE_CUSTOMER_IFRAME = 'https://sso-balancer2.testing.srv.loc/auth/admin/user/console?iframe=1&hiddenHeader=true'
