export const TYPES = {
  SET_POINTS: 'SET_POINTS',
  DELETE_POINTS: 'DELETE_POINTS',
  SET_POINTS_IS_LOADED: 'SET_POINTS_IS_LOADED',

  SET_DOMAINS: 'SET_DOMAINS',
  DELETE_DOMAINS: 'DELETE_DOMAINS',
  SET_DOMAINS_IS_LOADED: 'SET_DOMAINS_IS_LOADED',

  SET_DOMAIN_USER_COUNT: 'SET_DOMAIN_USER_COUNT',

  SET_ALLOWED_OFFERS: 'SET_ALLOWED_OFFERS',
  DELETE_ALLOWED_OFFERS: 'DELETE_ALLOWED_OFFERS',
  SET_ALLOWED_OFFERS_IS_LOADED: 'SET_ALLOWED_OFFERS_IS_LOADED'
}
