export const TYPES = {
  SET_POINTS: 'SET_POINTS',
  DELETE_POINTS: 'DELETE_POINTS',
  SET_POINTS_IS_LOADED: 'SET_POINTS_IS_LOADED',

  SET_DOMAINS: 'SET_DOMAINS',
  DELETE_DOMAINS: 'DELETE_DOMAINS',

  SET_ENFORTA_REGISTRY: 'SET_ENFORTA_REGISTRY',
  DELETE_ENFORTA_REGISTRY: 'DELETE_ENFORTA_REGISTRY',

  SET_VC_DATA_IS_LOADED: 'SET_VC_DATA_IS_LOADED',
  SET_ENFORTA_DATA_IS_LOADED: 'SET_ENFORTA_DATA_IS_LOADED',

  SET_DOMAIN_USER_COUNT: 'SET_DOMAIN_USER_COUNT',

  SET_ALLOWED_OFFERS: 'SET_ALLOWED_OFFERS',
  DELETE_ALLOWED_OFFERS: 'DELETE_ALLOWED_OFFERS',
  SET_ALLOWED_OFFERS_IS_LOADED: 'SET_ALLOWED_OFFERS_IS_LOADED',

  SET_PRODUCT_TYPE: 'SET_PRODUCT_TYPE',
  UNSET_PRODUCT_TYPE: 'UNSET_PRODUCT_TYPE'
}
